import sys

"""
Problem Description Link: https://projecteuler.net/problem=2

Problem Description:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

# Gather our code in a main() function
def main(count):
	Fibonacci_Numbers = [1, 2]

	for i in range(2, count):
		Fibonacci_Numbers.append(Fibonacci_Numbers[i-1] + Fibonacci_Numbers[i-2])

	print(Fibonacci_Numbers)



# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':

	try:
		count = int(input('Please enter a number: '))
	except Exception as e:
		print('Your Input is not valid. (Used Default Value: 10)')
		count = 10

	main(count)
